### ISSUE TITLE
Calling GitHub with a personal token

### ISSUE THREAD

**Issue by arcaartem** [ychen-97/alfred-github-star#2]
Hello,

Thanks for creating this workflow, it's quite handy! 😃 

Initially I had issues with it though. I consistently got rate limited whenever I tried to use the workflow. You see, I have starred nearly 2K of repos so far, and GitHub's anonymous access rate limits are not enough to allow the workflow to completely fetch them all! 😅

Hope you don't mind, as I've already created [a PR](https://github.com/yinan-c/alfred-github-star/pull/1) to allow setting a personal token so that requests to GitHub are subject to higher rate-limits. Having that allowed the workflow to completely fetch my stars!

Please feel free to do whatever you see fit with the PR. Once again, thanks for the workflow!

**Comment by yinan-c** [comment]
Hi,

Thank you for your contribution, your changes have been merged successfully. And I've added a new [release](https://github.com/yinan-c/alfred-github-star/releases/tag/v1.2) according to the issue, let me know if the new binary works.

**Comment by arcaartem** [comment]
Thank you!

I've tried it it works!

I don't know if it matters, but I had to manually install the `requests` library this time, though. I didn't have to do that when I originally installed the workflow through Alfred Gallery.

**Comment by yinan-c** [comment]
Ah, I see. There is one line missing `export PYTHONPATH='./dependency/'` - I must have forgotten to update the info.plist in the repo after I submit it to the Gallery.

Thanks for trying it out and spotting this!
