### ISSUE TITLE
Stars stuck Fetching, then getting rate limit even with personal key 

### ISSUE THREAD

**Issue by drewbitt** [ychen-97/alfred-github-star#3]
This is with a personal key for a higher rate limit. I have about 1.7k stars. Loading my stars with ghs works probably 1/4th of the time - it mostly just stalls at Fetching

![image](https://github.com/yinan-c/alfred-github-star/assets/26885897/22f7d274-f950-400f-92e5-dcc7387c5f33)

And then if I try it again once or twice, I get the rate limit. I assume because it is not caching the first response as it never came. 

<img width="742" alt="image" src="https://github.com/yinan-c/alfred-github-star/assets/26885897/d17390c2-6a41-4e54-8609-74fdd00880ea">

Let me know how to debug this for you.

**Comment by yinan-c** [comment]
Hi, thanks for your bug report. I am able to see the rate limit error if I constantly try recalling the workflow, but after a while, the results would still be there. I guess the first call was done in the background and successfully return some results for me. 

Is this the case for you?

**Comment by drewbitt** [comment]
Right, no, I dont get results at first so if I call it 2 or 3 times I hit the rate limit. The easier fix is to figure out why I'm not getting results very often and then I shouldn't have to retry.

**Comment by yinan-c** [comment]
I think if you call first time and wait for some time, given that you have so many stars (I think you don't have to wait while Alfred is on the screen). It should give you results, let me know the if the trick works.

I think the reason you got rate limit might be that you keeping calling github API in a very short amount of time.
